# This file contains values from Cookiecutter

default_context:
  project_name: "bb_project_new"
  project_slug: "bb_project"
  project_description: "Awesome `bb_project_new` project!"
  username: "letisaudep"
  email: "letisaudep@gmail.com"
  vcs_remote_type: "github"
  minimal_python_version: "3.8"
  version: "0.1.0"
  line_length: "88"

  include_cli_example: "n"
  include_docker_sample: "n"
  include_tests_sample: "y"
  include_notebooks_sample: "y"
  include_mypy_linter: "n"
